# Generated by Django 4.2.5 on 2023-09-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('idIngredient', models.AutoField(primary_key=True, serialize=False)),
                ('nomIngredient', models.CharField(max_length=50, verbose_name='le nom')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('idIPizza', models.AutoField(primary_key=True, serialize=False)),
                ('nomPizza', models.CharField(max_length=50, verbose_name='le nom de cette Pizza')),
            ],
        ),
    ]
