# Generated by Django 4.2.5 on 2023-09-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applipizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='le prix'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('idComposition', models.AutoField(primary_key=True, serialize=False)),
                ('pizza', models.CharField(max_length=100, verbose_name='la quantité')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applipizza.ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'pizza')},
            },
        ),
    ]
