# Generated by Django 4.2.5 on 2023-09-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applipizza', '0002_pizza_prix_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='quantite',
            field=models.CharField(default=0, max_length=100, verbose_name='la quantité'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='composition',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applipizza.pizza'),
        ),
    ]
