# Generated by Django 4.2.6 on 2023-12-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applipizza', '0003_composition_quantite_alter_composition_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='imagesPizzas/default.PNG', upload_to='imagesPizzas/'),
        ),
    ]
